# pacman is a "package manager" that defines the p_load function.
# p_load automatically installs a library if it is not already installed.
# This often, but doesn't always, works.
suppressPackageStartupMessages(library(pacman)) 
suppressPackageStartupMessages(library(Seurat))
suppressPackageStartupMessages(p_load(hdf5r))
suppressPackageStartupMessages(p_load(ggplot2))
suppressPackageStartupMessages(p_load(patchwork))
suppressPackageStartupMessages(p_load(dplyr))
suppressPackageStartupMessages(p_load(plyr))
suppressPackageStartupMessages(p_load(cowplot))
# suppressPackageStartupMessages(p_load(scales))
suppressPackageStartupMessages(p_load(reshape2))
suppressPackageStartupMessages(p_load(ggbeeswarm))
# suppressPackageStartupMessages(library(devtools))
# install_github("jokergoo/ComplexHeatmap")
suppressPackageStartupMessages(p_load(ComplexHeatmap))
# devtools::install_github("sjmgarnier/viridisLite")
suppressPackageStartupMessages(library(viridisLite))
suppressPackageStartupMessages(library(dendextend))
# suppressPackageStartupMessages(p_load(CCA))
# suppressPackageStartupMessages(p_load("sRDA"))
suppressPackageStartupMessages(p_load(PMA))
suppressPackageStartupMessages(p_load(ggpubr))
suppressPackageStartupMessages(p_load(rstatix))
suppressPackageStartupMessages(p_load(gtools))
suppressPackageStartupMessages(p_load(DropletUtils)) # for downsampling count matrices
suppressPackageStartupMessages(p_load(foreach))
suppressPackageStartupMessages(p_load(parallel))
suppressPackageStartupMessages(p_load(scran)) # for deconvolution-based normalization
suppressPackageStartupMessages(p_load(scuttle)) # for deconvolution-based normalization
suppressPackageStartupMessages(p_load(rjson))
##if (!require(devtools)) install.packages("devtools")
##devtools::install_github("gaospecial/ggVennDiagram")
suppressPackageStartupMessages(p_load(ggVennDiagram))
suppressPackageStartupMessages(p_load(gridExtra))
suppressPackageStartupMessages(p_load(biomaRt))
suppressPackageStartupMessages(p_load(gplots))
suppressPackageStartupMessages(p_load(RColorBrewer))
suppressPackageStartupMessages(p_load(harmony))
#devtools::install_github("dmcable/spacexr", build_vignettes = FALSE)
suppressPackageStartupMessages(p_load(spacexr))
suppressPackageStartupMessages(p_load(Matrix))
suppressPackageStartupMessages(p_load(doParallel))
suppressPackageStartupMessages(p_load(sf))
suppressPackageStartupMessages(p_load(spdep))
#if (!require("BiocManager", quietly = TRUE))
#    install.packages("BiocManager")
#BiocManager::install("RITAN")
suppressPackageStartupMessages(p_load(RITAN))
suppressPackageStartupMessages(p_load(RITANdata))
#if (!require("BiocManager", quietly = TRUE))
#    install.packages("BiocManager")
#BiocManager::install("org.Hs.eg.db")
suppressPackageStartupMessages(p_load(org.Hs.eg.db))
suppressPackageStartupMessages(p_load(org.Mm.eg.db))
#if (!require("BiocManager", quietly = TRUE))
#    install.packages("BiocManager")
#BiocManager::install("GOSemSim")
suppressPackageStartupMessages(p_load(GOSemSim))
#    install.packages("BiocManager")
#BiocManager::install("clusterProfiler")
suppressPackageStartupMessages(p_load(clusterProfiler))
suppressPackageStartupMessages(p_load(enrichplot))
suppressPackageStartupMessages(p_load(ggnewscale))

suppressPackageStartupMessages(p_load(data.table))
suppressPackageStartupMessages(p_load(rhdf5))
suppressPackageStartupMessages(p_load(devtools))
suppressPackageStartupMessages(p_load(Rsamtools))
suppressPackageStartupMessages(p_load(edgeR))
suppressPackageStartupMessages(p_load(ggExtra))
#require(remotes)
#remotes::install_github('JEFworks-Lab/STdeconvolve')
suppressPackageStartupMessages(p_load(STdeconvolve))
suppressPackageStartupMessages(p_load(corrplot))
suppressPackageStartupMessages(p_load(limma))
suppressPackageStartupMessages(p_load(hexbin))

source("util_functions.R")
source("plot_util_functions.R")



filenames<-c('/pod/2/activities/jaxcc/CATch-project/raw-data/visium/analysis_dir/Endometrium/Endometrium.csv','/pod/2/activities/jaxcc/CATch-project/raw-data/visium/analysis_dir/Colon/Colon.csv','/pod/2/activities/jaxcc/CATch-project/raw-data/visium/analysis_dir/Pdac/pdac.csv','/pod/2/activities/jaxcc/CATch-project/raw-data/visium/analysis_dir/Colon//pod/2/activities/jaxcc/CATch-project/raw-data/visium/analysis_dir/Colon/Colon.csv','/pod/2/activities/jaxcc/CATch-project/raw-data/visium/analysis_dir/Breast_1/breastcancer.csv')
datasets.data<-list()
for (i in 1:length(filenames)){
  datasets.data[[i]]<-calculate.qc.functions(filenames[i]) 
  names(datasets.data)[i]<-as.character(datasets.data[[i]][["metadata"]][["tissue_type"]])[1]
  plot.qc.data(datasets.data[[i]])
}